name: Sync repos

on:
  push:
    branches: [main]
    paths: ["packages/react/**"]
  pull_request:
    branches: [main]
    paths: ["packages/react/**"]

jobs:
  sync:
    name: Sync React Package to Public Repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for subtree

      - name: Setup GitHub CLI
        run: |
          git config credential.helper '!f() { echo username=speakeasybot; echo "password=${{ secrets.DOCS_MD_REACT_GITHUB_TOKEN }}"; };f'

      - name: Add public remote
        run: git remote add public-react https://github.com/speakeasy-api/docs-md-react.git

      - name: Push to public repo
        run: git subtree push --prefix=packages/react public-react main
